[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "Vaulted is a secure credential management utility"
edition = "2021"
homepage = "https://gihub.com/FL03/vaulted/wiki"
keywords = []
license = "Apache-2.0"
name = "vaulted-cli"
publish = true
repository = "https://gihub.com/FL03/vaulted"
version = "0.1.8"

[[bin]]
name = "vaulted"
path = "src/main.rs"

[build-dependencies]

[dependencies]
clap = { features = ["derive"], version = "4.0.29" }
csv = "1.1.6"
log = "0.4.17"
lru = "0.8.1"
provider-archive = "0.6.0"
scsys = { features = ["full"], version = "0.1.35" }
serde = { features = ["derive"], version = "1.0.148" }
serde_json = "1.0.89"
strum = { features = ["derive"], version = "0.24.1" }
tokio = { features = ["full"], version = "1.22.0" }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
vaulted = { path = "../lib" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]